server:
  port: ${PORT:0}

spring:
  application:
    name: customer

eureka:
  instance:
    appname: customer
#    metadata-map:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Customer Sample Application
    description: Description
    version: 1.0.0

management:
  endpoint:
    configprops:
      enabled: true
    health:
      show-details: always
